apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: {{ .Values.operator.packageName | quote }}
spec:
  namespace: {{ .Values.operator.namespace | quote }}
  source:
    sourceType: Catalog
    catalog:
      packageName: {{ .Values.operator.packageName | quote }}
      channels:
      - {{ .Values.operator.channel | quote }}
      version: {{ .Values.operator.versionRange | quote }}
      upgradeConstraintPolicy: {{ .Values.operator.upgradeConstraintPolicy | quote }}
      selector:
        matchLabels:
          olm.operatorframework.io/metadata.name: {{ .Values.operator.catalogName | quote }}
  install:
    preflight:
      crdUpgradeSafety:
        enforcement: Strict
