apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.name | quote }}
  namespace: {{ .Values.namespace.olm | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.secret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.name | quote }}
  namespace: {{ .Values.namespace.system | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.secret | quote }}
