apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: neteye-operator.v0.0.0
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    alm-examples: |-
      [{"apiVersion":"neteye.cloud/v1alpha1","kind":"NetEye","metadata":{"name":"neteye-sample"},"spec":{"version":"4.51","gateway":{"name":"neteye","className":"cilium"},"internalCertificateIssuerRef":"neteye-internal-issuer","identity":{"hostname":"keycloak.example.com","dbConnection":{"host":"mariadb.example.com","dbName":"keycloak","usernameSecret":{"name":"keycloak-db-secret","key":"username"},"passwordSecret":{"name":"keycloak-db-secret","key":"password"}}},"elasticStack":{"enabled":true,"elasticsearchEndpoints":["https://192.0.2.10:9200"],"telemetry":{"otelCollector":{},"edotGateway":{}}}}}]
spec:
  displayName: NetEye Operator
  description: NetEye Operator for managing cloud-native infrastructure
  maturity: alpha
  minKubeVersion: 1.36.0
  provider:
    name: Wuerth IT | Italy
  maintainers:
    - name: Wuerth IT | Italy
      email: info.italy@wuerth-it.com
  links:
    - name: NetEye
      url: https://neteye.guide/
  keywords:
    - neteye
    - operator
  relatedImages:
    - name: neteye-keycloak
      image: ghcr.io/neteye-platform/neteye-keycloak:1.0.6@sha256:e58681c26f89d305d87a38ce20b81bfb8dfd47fc5d6068ebec2a609bf89c3ce2
    - name: neteye-otel-collector
      image: docker.io/otel/opentelemetry-collector-contrib:0.161.0@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1
    - name: neteye-edot-gateway
      image: docker.elastic.co/elastic-agent/elastic-otel-collector:9.5.4@sha256:0597fe7cad118fcaee15a8691088eff7b60fdd1501bd84fc91b90066d79c9afd
    - name: neteye-ca-bundle
      image: docker.io/alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
  install:
    strategy: deployment
