apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: neteye-operator.v0.0.0
  namespace: placeholder
  annotations:
    capabilities: Basic Install
    alm-examples: |-
      [{"apiVersion":"neteye.cloud/v1alpha1","kind":"NetEye","metadata":{"name":"neteye-sample"},"spec":{"version":"4.50","gateway":{"name":"neteye","className":"cilium"},"internalCertificateIssuerRef":"neteye-internal-issuer","identity":{"hostname":"keycloak.example.com","dbConnection":{"host":"mariadb.example.com","dbName":"keycloak","usernameSecret":{"name":"keycloak-db-secret","key":"username"},"passwordSecret":{"name":"keycloak-db-secret","key":"password"}}}}}]
spec:
  displayName: NetEye Operator
  description: NetEye Operator for managing cloud-native infrastructure
  maturity: alpha
  minKubeVersion: 1.36.0
  provider:
    name: Wuerth IT | Italy
  maintainers:
    - name: Wuerth IT | Italy
      email: info.italy@wuerth-it.com
  links:
    - name: NetEye
      url: https://neteye.guide/
  keywords:
    - neteye
    - operator
  relatedImages:
    - name: neteye-keycloak
      image: ghcr.io/neteye-platform/neteye-keycloak:1.0.4
    - name: neteye-otel-collector
      image: docker.io/otel/opentelemetry-collector-contrib:0.156.0
  install:
    strategy: deployment
