apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: neteye-operator.v0.0.0
  namespace: placeholder
spec:
  webhookdefinitions:
    - type: ValidatingAdmissionWebhook
      generateName: vneteye-v1alpha1.neteye.cloud
      deploymentName: neteye-operator
      containerPort: 9443
      targetPort: 9443
      webhookPath: /validate-neteye-cloud-v1alpha1-neteye
      admissionReviewVersions: [v1]
      failurePolicy: Fail
      sideEffects: None
      rules:
        - apiGroups: [neteye.cloud]
          apiVersions: [v1alpha1]
          operations: [CREATE, UPDATE]
          resources: [neteyes]
          scope: Namespaced
