// SPDX-FileCopyrightText: 2026 Würth IT Italy S.r.l.
// SPDX-License-Identifier: Apache-2.0 OR MIT

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KeycloakRealmSpec defines the desired state of a Keycloak realm.
type KeycloakRealmSpec struct {
	// Realm is the name of the Keycloak realm.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Realm string `json:"realm"`

	// DisplayName is the display name of the realm.
	// +kubebuilder:validation:Optional
	DisplayName string `json:"displayName,omitempty"`

	// DisplayNameHTML is the HTML display name of the realm.
	// +kubebuilder:validation:Optional
	DisplayNameHTML string `json:"displayNameHtml,omitempty"`

	// DefaultSignatureAlgorithm is the default signature algorithm used by the realm.
	// +kubebuilder:validation:Optional
	DefaultSignatureAlgorithm string `json:"defaultSignatureAlgorithm,omitempty"`

	// RevokeRefreshToken determines whether refresh tokens are revoked after use.
	// +kubebuilder:validation:Optional
	RevokeRefreshToken bool `json:"revokeRefreshToken,omitempty"`

	// RefreshTokenMaxReuse is the maximum number of times a refresh token can be reused.
	// +kubebuilder:validation:Optional
	RefreshTokenMaxReuse int32 `json:"refreshTokenMaxReuse,omitempty"`

	// AccessTokenLifespan is the default access token lifespan in seconds.
	// +kubebuilder:validation:Optional
	AccessTokenLifespan int32 `json:"accessTokenLifespan,omitempty"`

	// AccessTokenLifespanForImplicitFlow is the access token lifespan for implicit flows in seconds.
	// +kubebuilder:validation:Optional
	AccessTokenLifespanForImplicitFlow int32 `json:"accessTokenLifespanForImplicitFlow,omitempty"`

	// SSOSessionIdleTimeout is the SSO session idle timeout in seconds.
	// +kubebuilder:validation:Optional
	SSOSessionIdleTimeout int32 `json:"ssoSessionIdleTimeout,omitempty"`

	// SSOSessionMaxLifespan is the maximum SSO session lifespan in seconds.
	// +kubebuilder:validation:Optional
	SSOSessionMaxLifespan int32 `json:"ssoSessionMaxLifespan,omitempty"`

	// SSOSessionIdleTimeoutRememberMe is the SSO session idle timeout for remember-me sessions in seconds.
	// +kubebuilder:validation:Optional
	SSOSessionIdleTimeoutRememberMe int32 `json:"ssoSessionIdleTimeoutRememberMe,omitempty"`

	// SSOSessionMaxLifespanRememberMe is the maximum SSO session lifespan for remember-me sessions in seconds.
	// +kubebuilder:validation:Optional
	SSOSessionMaxLifespanRememberMe int32 `json:"ssoSessionMaxLifespanRememberMe,omitempty"`

	// OfflineSessionIdleTimeout is the offline session idle timeout in seconds.
	// +kubebuilder:validation:Optional
	OfflineSessionIdleTimeout int32 `json:"offlineSessionIdleTimeout,omitempty"`

	// OfflineSessionMaxLifespanEnabled determines whether a maximum offline session lifespan is enforced.
	// +kubebuilder:validation:Optional
	OfflineSessionMaxLifespanEnabled bool `json:"offlineSessionMaxLifespanEnabled,omitempty"`

	// OfflineSessionMaxLifespan is the maximum offline session lifespan in seconds.
	// +kubebuilder:validation:Optional
	OfflineSessionMaxLifespan int32 `json:"offlineSessionMaxLifespan,omitempty"`

	// ClientSessionIdleTimeout is the client session idle timeout in seconds.
	// +kubebuilder:validation:Optional
	ClientSessionIdleTimeout int32 `json:"clientSessionIdleTimeout,omitempty"`

	// ClientSessionMaxLifespan is the maximum client session lifespan in seconds.
	// +kubebuilder:validation:Optional
	ClientSessionMaxLifespan int32 `json:"clientSessionMaxLifespan,omitempty"`

	// ClientOfflineSessionIdleTimeout is the client offline session idle timeout in seconds.
	// +kubebuilder:validation:Optional
	ClientOfflineSessionIdleTimeout int32 `json:"clientOfflineSessionIdleTimeout,omitempty"`

	// ClientOfflineSessionMaxLifespan is the maximum client offline session lifespan in seconds.
	// +kubebuilder:validation:Optional
	ClientOfflineSessionMaxLifespan int32 `json:"clientOfflineSessionMaxLifespan,omitempty"`

	// AccessCodeLifespan is the access code lifespan in seconds.
	// +kubebuilder:validation:Optional
	AccessCodeLifespan int32 `json:"accessCodeLifespan,omitempty"`

	// AccessCodeLifespanUserAction is the access code lifespan for user actions in seconds.
	// +kubebuilder:validation:Optional
	AccessCodeLifespanUserAction int32 `json:"accessCodeLifespanUserAction,omitempty"`

	// AccessCodeLifespanLogin is the access code lifespan for login in seconds.
	// +kubebuilder:validation:Optional
	AccessCodeLifespanLogin int32 `json:"accessCodeLifespanLogin,omitempty"`

	// ActionTokenGeneratedByAdminLifespan is the lifespan of action tokens generated by an admin in seconds.
	// +kubebuilder:validation:Optional
	ActionTokenGeneratedByAdminLifespan int32 `json:"actionTokenGeneratedByAdminLifespan,omitempty"`

	// ActionTokenGeneratedByUserLifespan is the lifespan of action tokens generated by a user in seconds.
	// +kubebuilder:validation:Optional
	ActionTokenGeneratedByUserLifespan int32 `json:"actionTokenGeneratedByUserLifespan,omitempty"`

	// OAuth2DeviceCodeLifespan is the OAuth2 device authorization code lifespan in seconds.
	// +kubebuilder:validation:Optional
	OAuth2DeviceCodeLifespan int32 `json:"oauth2DeviceCodeLifespan,omitempty"`

	// OAuth2DevicePollingInterval is the OAuth2 device authorization polling interval in seconds.
	// +kubebuilder:validation:Optional
	OAuth2DevicePollingInterval int32 `json:"oauth2DevicePollingInterval,omitempty"`

	// Enabled determines whether the realm is enabled.
	// +kubebuilder:validation:Optional
	Enabled bool `json:"enabled,omitempty"`

	// SSLRequired defines the SSL requirement for the realm.
	// +kubebuilder:validation:Optional
	SSLRequired string `json:"sslRequired,omitempty"`

	// RegistrationAllowed determines whether user registration is allowed.
	// +kubebuilder:validation:Optional
	RegistrationAllowed bool `json:"registrationAllowed,omitempty"`

	// RegistrationEmailAsUsername determines whether the user's email address is used as their username during registration.
	// +kubebuilder:validation:Optional
	RegistrationEmailAsUsername bool `json:"registrationEmailAsUsername,omitempty"`

	// RememberMe determines whether the remember-me option is available.
	// +kubebuilder:validation:Optional
	RememberMe bool `json:"rememberMe,omitempty"`

	// VerifyEmail determines whether users must verify their email address.
	// +kubebuilder:validation:Optional
	VerifyEmail bool `json:"verifyEmail,omitempty"`

	// LoginWithEmailAllowed determines whether users can log in using their email address.
	// +kubebuilder:validation:Optional
	LoginWithEmailAllowed bool `json:"loginWithEmailAllowed,omitempty"`

	// DuplicateEmailsAllowed determines whether multiple users can have the same email address.
	// +kubebuilder:validation:Optional
	DuplicateEmailsAllowed bool `json:"duplicateEmailsAllowed,omitempty"`

	// ResetPasswordAllowed determines whether users can reset their passwords.
	// +kubebuilder:validation:Optional
	ResetPasswordAllowed bool `json:"resetPasswordAllowed,omitempty"`

	// EditUsernameAllowed determines whether users can edit their usernames.
	// +kubebuilder:validation:Optional
	EditUsernameAllowed bool `json:"editUsernameAllowed,omitempty"`

	// BruteForceProtected determines whether brute-force protection is enabled.
	// +kubebuilder:validation:Optional
	BruteForceProtected bool `json:"bruteForceProtected,omitempty"`

	// PermanentLockout determines whether users can be permanently locked out.
	// +kubebuilder:validation:Optional
	PermanentLockout bool `json:"permanentLockout,omitempty"`

	// MaxTemporaryLockouts is the maximum number of temporary lockouts.
	// +kubebuilder:validation:Optional
	MaxTemporaryLockouts int32 `json:"maxTemporaryLockouts,omitempty"`

	// BruteForceStrategy defines the strategy used for brute-force protection.
	// +kubebuilder:validation:Optional
	BruteForceStrategy string `json:"bruteForceStrategy,omitempty"`

	// MaxFailureWaitSeconds is the maximum login failure wait time in seconds.
	// +kubebuilder:validation:Optional
	MaxFailureWaitSeconds int32 `json:"maxFailureWaitSeconds,omitempty"`

	// MinimumQuickLoginWaitSeconds is the minimum quick-login wait time in seconds.
	// +kubebuilder:validation:Optional
	MinimumQuickLoginWaitSeconds int32 `json:"minimumQuickLoginWaitSeconds,omitempty"`

	// WaitIncrementSeconds is the amount by which the failure wait time is incremented.
	// +kubebuilder:validation:Optional
	WaitIncrementSeconds int32 `json:"waitIncrementSeconds,omitempty"`

	// QuickLoginCheckMilliSeconds is the quick-login check interval in milliseconds.
	// +kubebuilder:validation:Optional
	QuickLoginCheckMilliSeconds int32 `json:"quickLoginCheckMilliSeconds,omitempty"`

	// MaxDeltaTimeSeconds is the maximum delta time used for brute-force detection in seconds.
	// +kubebuilder:validation:Optional
	MaxDeltaTimeSeconds int32 `json:"maxDeltaTimeSeconds,omitempty"`

	// FailureFactor is the number of failures allowed before triggering brute-force protection.
	// +kubebuilder:validation:Optional
	FailureFactor int32 `json:"failureFactor,omitempty"`

	// MaxSecondaryAuthFailures is the maximum number of secondary authentication failures.
	// +kubebuilder:validation:Optional
	MaxSecondaryAuthFailures int32 `json:"maxSecondaryAuthFailures,omitempty"`

	// OTPPolicyType defines the OTP policy type.
	// +kubebuilder:validation:Optional
	OTPPolicyType string `json:"otpPolicyType,omitempty"`

	// OTPPolicyAlgorithm defines the algorithm used by the OTP policy.
	// +kubebuilder:validation:Optional
	OTPPolicyAlgorithm string `json:"otpPolicyAlgorithm,omitempty"`

	// OTPPolicyInitialCounter is the initial OTP counter value.
	// +kubebuilder:validation:Optional
	OTPPolicyInitialCounter int32 `json:"otpPolicyInitialCounter,omitempty"`

	// OTPPolicyDigits is the number of digits generated by the OTP policy.
	// +kubebuilder:validation:Optional
	OTPPolicyDigits int32 `json:"otpPolicyDigits,omitempty"`

	// OTPPolicyLookAheadWindow is the OTP look-ahead window.
	// +kubebuilder:validation:Optional
	OTPPolicyLookAheadWindow int32 `json:"otpPolicyLookAheadWindow,omitempty"`

	// OTPPolicyPeriod is the OTP token period in seconds.
	// +kubebuilder:validation:Optional
	OTPPolicyPeriod int32 `json:"otpPolicyPeriod,omitempty"`

	// OTPPolicyCodeReusable determines whether OTP codes can be reused.
	// +kubebuilder:validation:Optional
	OTPPolicyCodeReusable bool `json:"otpPolicyCodeReusable,omitempty"`

	// OTPSupportedApplications lists applications supported by the OTP policy.
	// +kubebuilder:validation:Optional
	OTPSupportedApplications []string `json:"otpSupportedApplications,omitempty"`

	// WebAuthnPolicyRpEntityName is the WebAuthn relying-party entity name.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyRpEntityName string `json:"webAuthnPolicyRpEntityName,omitempty"`

	// WebAuthnPolicySignatureAlgorithms lists supported WebAuthn signature algorithms.
	// +kubebuilder:validation:Optional
	WebAuthnPolicySignatureAlgorithms []string `json:"webAuthnPolicySignatureAlgorithms,omitempty"`

	// WebAuthnPolicyRpID is the WebAuthn relying-party ID.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyRpID string `json:"webAuthnPolicyRpId,omitempty"`

	// WebAuthnPolicyAttestationConveyancePreference defines the WebAuthn attestation conveyance preference.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyAttestationConveyancePreference string `json:"webAuthnPolicyAttestationConveyancePreference,omitempty"`

	// WebAuthnPolicyAuthenticatorAttachment defines the preferred authenticator attachment.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyAuthenticatorAttachment string `json:"webAuthnPolicyAuthenticatorAttachment,omitempty"`

	// WebAuthnPolicyRequireResidentKey defines whether resident keys are required.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyRequireResidentKey string `json:"webAuthnPolicyRequireResidentKey,omitempty"`

	// WebAuthnPolicyResidentKey defines the resident key requirement.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyResidentKey string `json:"webAuthnPolicyResidentKey,omitempty"`

	// WebAuthnPolicyUserVerificationRequirement defines the user verification requirement.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyUserVerificationRequirement string `json:"webAuthnPolicyUserVerificationRequirement,omitempty"`

	// WebAuthnPolicyCreateTimeout is the WebAuthn credential creation timeout in milliseconds.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyCreateTimeout int32 `json:"webAuthnPolicyCreateTimeout,omitempty"`

	// WebAuthnPolicyAvoidSameAuthenticatorRegister determines whether the same authenticator
	// can be registered more than once.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyAvoidSameAuthenticatorRegister bool `json:"webAuthnPolicyAvoidSameAuthenticatorRegister,omitempty"`

	// WebAuthnPolicyAcceptableAAGUIDs lists acceptable WebAuthn authenticator AAGUIDs.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyAcceptableAAGUIDs []string `json:"webAuthnPolicyAcceptableAaguids,omitempty"`

	// WebAuthnPolicyExtraOrigins lists additional origins accepted by the WebAuthn policy.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyExtraOrigins []string `json:"webAuthnPolicyExtraOrigins,omitempty"`

	// WebAuthnPolicyPasswordlessRpEntityName is the relying-party entity name for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessRpEntityName string `json:"webAuthnPolicyPasswordlessRpEntityName,omitempty"`

	// WebAuthnPolicyPasswordlessSignatureAlgorithms lists supported signature algorithms
	// for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessSignatureAlgorithms []string `json:"webAuthnPolicyPasswordlessSignatureAlgorithms,omitempty"`

	// WebAuthnPolicyPasswordlessRpID is the relying-party ID for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessRpID string `json:"webAuthnPolicyPasswordlessRpId,omitempty"`

	// WebAuthnPolicyPasswordlessAttestationConveyancePreference defines the attestation
	// conveyance preference for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessAttestationConveyancePreference string `json:"webAuthnPolicyPasswordlessAttestationConveyancePreference,omitempty"`

	// WebAuthnPolicyPasswordlessAuthenticatorAttachment defines the preferred authenticator
	// attachment for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessAuthenticatorAttachment string `json:"webAuthnPolicyPasswordlessAuthenticatorAttachment,omitempty"`

	// WebAuthnPolicyPasswordlessRequireResidentKey defines whether resident keys are required
	// for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessRequireResidentKey string `json:"webAuthnPolicyPasswordlessRequireResidentKey,omitempty"`

	// WebAuthnPolicyPasswordlessResidentKey defines the resident key requirement for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessResidentKey string `json:"webAuthnPolicyPasswordlessResidentKey,omitempty"`

	// WebAuthnPolicyPasswordlessUserVerificationRequirement defines the user verification
	// requirement for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessUserVerificationRequirement string `json:"webAuthnPolicyPasswordlessUserVerificationRequirement,omitempty"`

	// WebAuthnPolicyPasswordlessCreateTimeout is the passwordless WebAuthn credential creation
	// timeout in milliseconds.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessCreateTimeout int32 `json:"webAuthnPolicyPasswordlessCreateTimeout,omitempty"`

	// WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister determines whether the same
	// authenticator can be registered more than once for passwordless WebAuthn.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister bool `json:"webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister,omitempty"`

	// WebAuthnPolicyPasswordlessAcceptableAAGUIDs lists acceptable WebAuthn authenticator
	// AAGUIDs for passwordless authentication.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessAcceptableAAGUIDs []string `json:"webAuthnPolicyPasswordlessAcceptableAaguids,omitempty"`

	// WebAuthnPolicyPasswordlessExtraOrigins lists additional origins accepted by the
	// passwordless WebAuthn policy.
	// +kubebuilder:validation:Optional
	WebAuthnPolicyPasswordlessExtraOrigins []string `json:"webAuthnPolicyPasswordlessExtraOrigins,omitempty"`

	// BrowserSecurityHeaders contains browser security headers applied by Keycloak.
	// +kubebuilder:validation:Optional
	BrowserSecurityHeaders map[string]string `json:"browserSecurityHeaders,omitempty"`

	// SMTPServer contains the SMTP server configuration.
	// +kubebuilder:validation:Optional
	SMTPServer map[string]string `json:"smtpServer,omitempty"`

	// LoginTheme is the theme used by the login pages.
	// +kubebuilder:validation:Optional
	LoginTheme string `json:"loginTheme,omitempty"`

	// AccountTheme is the theme used by the account console.
	// +kubebuilder:validation:Optional
	AccountTheme string `json:"accountTheme,omitempty"`

	// AdminTheme is the theme used by the administration console.
	// +kubebuilder:validation:Optional
	AdminTheme string `json:"adminTheme,omitempty"`

	// EmailTheme is the theme used for emails.
	// +kubebuilder:validation:Optional
	EmailTheme string `json:"emailTheme,omitempty"`

	// EventsEnabled determines whether user events are enabled.
	// +kubebuilder:validation:Optional
	EventsEnabled bool `json:"eventsEnabled,omitempty"`

	// EventsExpiration is the duration for which events are retained in seconds.
	// +kubebuilder:validation:Optional
	EventsExpiration int32 `json:"eventsExpiration,omitempty"`

	// EventsListeners lists the event listeners enabled for the realm.
	// +kubebuilder:validation:Optional
	EventsListeners []string `json:"eventsListeners,omitempty"`

	// EnabledEventTypes lists the event types enabled for the realm.
	// +kubebuilder:validation:Optional
	EnabledEventTypes []string `json:"enabledEventTypes,omitempty"`

	// AdminEventsEnabled determines whether admin events are enabled.
	// +kubebuilder:validation:Optional
	AdminEventsEnabled bool `json:"adminEventsEnabled,omitempty"`

	// AdminEventsDetailsEnabled determines whether details are included in admin events.
	// +kubebuilder:validation:Optional
	AdminEventsDetailsEnabled bool `json:"adminEventsDetailsEnabled,omitempty"`

	// InternationalizationEnabled determines whether internationalization is enabled.
	// +kubebuilder:validation:Optional
	InternationalizationEnabled bool `json:"internationalizationEnabled,omitempty"`

	// Attributes contains custom Keycloak realm attributes.
	// +kubebuilder:validation:Optional
	Attributes map[string]string `json:"attributes,omitempty"`

	// UserManagedAccessAllowed determines whether user-managed access is allowed.
	// +kubebuilder:validation:Optional
	UserManagedAccessAllowed bool `json:"userManagedAccessAllowed,omitempty"`

	// OrganizationsEnabled determines whether organizations are enabled.
	// +kubebuilder:validation:Optional
	OrganizationsEnabled bool `json:"organizationsEnabled,omitempty"`

	// VerifiableCredentialsEnabled determines whether verifiable credentials are enabled.
	// +kubebuilder:validation:Optional
	VerifiableCredentialsEnabled bool `json:"verifiableCredentialsEnabled,omitempty"`

	// AdminPermissionsEnabled determines whether admin permissions are enabled.
	// +kubebuilder:validation:Optional
	AdminPermissionsEnabled bool `json:"adminPermissionsEnabled,omitempty"`

	// SCIMAPIEnabled determines whether the SCIM API is enabled.
	// +kubebuilder:validation:Optional
	SCIMAPIEnabled bool `json:"scimApiEnabled,omitempty"`
}

// KeycloakRealmStatus defines the observed state of KeycloakRealm.
type KeycloakRealmStatus struct {
	// ID is the Keycloak internal ID of the realm.
	// +kubebuilder:validation:Optional
	ID string `json:"id,omitempty"`

	// Value is the reconciliation status.
	// +kubebuilder:validation:Optional
	Value string `json:"value,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=keycloakrealms,shortName=kcrealm
// +kubebuilder:printcolumn:name="Realm",type=string,JSONPath=`.spec.realm`
// +kubebuilder:printcolumn:name="Status",type=string,JSONPath=`.status.value`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// KeycloakRealm is the Schema for the keycloakrealms API.
type KeycloakRealm struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   KeycloakRealmSpec   `json:"spec,omitempty"`
	Status KeycloakRealmStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeycloakRealmList contains a list of KeycloakRealm.
type KeycloakRealmList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeycloakRealm `json:"items"`
}