//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 Würth IT Italy S.r.l.
// SPDX-License-Identifier: Apache-2.0 OR MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlow) DeepCopyInto(out *KeycloakAuthFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlow.
func (in *KeycloakAuthFlow) DeepCopy() *KeycloakAuthFlow {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakAuthFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowConfig) DeepCopyInto(out *KeycloakAuthFlowConfig) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowConfig.
func (in *KeycloakAuthFlowConfig) DeepCopy() *KeycloakAuthFlowConfig {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowExecution) DeepCopyInto(out *KeycloakAuthFlowExecution) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(KeycloakAuthFlowConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Flow != nil {
		in, out := &in.Flow, &out.Flow
		*out = new(KeycloakAuthFlowSubflow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowExecution.
func (in *KeycloakAuthFlowExecution) DeepCopy() *KeycloakAuthFlowExecution {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowList) DeepCopyInto(out *KeycloakAuthFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakAuthFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowList.
func (in *KeycloakAuthFlowList) DeepCopy() *KeycloakAuthFlowList {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakAuthFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowSpec) DeepCopyInto(out *KeycloakAuthFlowSpec) {
	*out = *in
	if in.Executions != nil {
		in, out := &in.Executions, &out.Executions
		*out = make([]KeycloakAuthFlowExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowSpec.
func (in *KeycloakAuthFlowSpec) DeepCopy() *KeycloakAuthFlowSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowStatus) DeepCopyInto(out *KeycloakAuthFlowStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowStatus.
func (in *KeycloakAuthFlowStatus) DeepCopy() *KeycloakAuthFlowStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakAuthFlowSubflow) DeepCopyInto(out *KeycloakAuthFlowSubflow) {
	*out = *in
	if in.Executions != nil {
		in, out := &in.Executions, &out.Executions
		*out = make([]KeycloakAuthFlowExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakAuthFlowSubflow.
func (in *KeycloakAuthFlowSubflow) DeepCopy() *KeycloakAuthFlowSubflow {
	if in == nil {
		return nil
	}
	out := new(KeycloakAuthFlowSubflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealm) DeepCopyInto(out *KeycloakRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealm.
func (in *KeycloakRealm) DeepCopy() *KeycloakRealm {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmList) DeepCopyInto(out *KeycloakRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmList.
func (in *KeycloakRealmList) DeepCopy() *KeycloakRealmList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmSpec) DeepCopyInto(out *KeycloakRealmSpec) {
	*out = *in
	if in.OTPSupportedApplications != nil {
		in, out := &in.OTPSupportedApplications, &out.OTPSupportedApplications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicySignatureAlgorithms != nil {
		in, out := &in.WebAuthnPolicySignatureAlgorithms, &out.WebAuthnPolicySignatureAlgorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyAcceptableAAGUIDs != nil {
		in, out := &in.WebAuthnPolicyAcceptableAAGUIDs, &out.WebAuthnPolicyAcceptableAAGUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyExtraOrigins != nil {
		in, out := &in.WebAuthnPolicyExtraOrigins, &out.WebAuthnPolicyExtraOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyPasswordlessSignatureAlgorithms != nil {
		in, out := &in.WebAuthnPolicyPasswordlessSignatureAlgorithms, &out.WebAuthnPolicyPasswordlessSignatureAlgorithms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyPasswordlessAcceptableAAGUIDs != nil {
		in, out := &in.WebAuthnPolicyPasswordlessAcceptableAAGUIDs, &out.WebAuthnPolicyPasswordlessAcceptableAAGUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebAuthnPolicyPasswordlessExtraOrigins != nil {
		in, out := &in.WebAuthnPolicyPasswordlessExtraOrigins, &out.WebAuthnPolicyPasswordlessExtraOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BrowserSecurityHeaders != nil {
		in, out := &in.BrowserSecurityHeaders, &out.BrowserSecurityHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SMTPServer != nil {
		in, out := &in.SMTPServer, &out.SMTPServer
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EventsListeners != nil {
		in, out := &in.EventsListeners, &out.EventsListeners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnabledEventTypes != nil {
		in, out := &in.EnabledEventTypes, &out.EnabledEventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmSpec.
func (in *KeycloakRealmSpec) DeepCopy() *KeycloakRealmSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmStatus) DeepCopyInto(out *KeycloakRealmStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmStatus.
func (in *KeycloakRealmStatus) DeepCopy() *KeycloakRealmStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEye) DeepCopyInto(out *NetEye) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEye.
func (in *NetEye) DeepCopy() *NetEye {
	if in == nil {
		return nil
	}
	out := new(NetEye)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetEye) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeComponents) DeepCopyInto(out *NetEyeComponents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeComponents.
func (in *NetEyeComponents) DeepCopy() *NetEyeComponents {
	if in == nil {
		return nil
	}
	out := new(NetEyeComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeDBConnectionSpec) DeepCopyInto(out *NetEyeDBConnectionSpec) {
	*out = *in
	out.UsernameSecret = in.UsernameSecret
	out.PasswordSecret = in.PasswordSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeDBConnectionSpec.
func (in *NetEyeDBConnectionSpec) DeepCopy() *NetEyeDBConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeDBConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeElasticStackSpec) DeepCopyInto(out *NetEyeElasticStackSpec) {
	*out = *in
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(NetEyeOtelCollectorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeElasticStackSpec.
func (in *NetEyeElasticStackSpec) DeepCopy() *NetEyeElasticStackSpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeElasticStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeElasticStackStatus) DeepCopyInto(out *NetEyeElasticStackStatus) {
	*out = *in
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(NetEyeServiceStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeElasticStackStatus.
func (in *NetEyeElasticStackStatus) DeepCopy() *NetEyeElasticStackStatus {
	if in == nil {
		return nil
	}
	out := new(NetEyeElasticStackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeGatewaySpec) DeepCopyInto(out *NetEyeGatewaySpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeGatewaySpec.
func (in *NetEyeGatewaySpec) DeepCopy() *NetEyeGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeIdentitySpec) DeepCopyInto(out *NetEyeIdentitySpec) {
	*out = *in
	if in.PodExtraEnvVars != nil {
		in, out := &in.PodExtraEnvVars, &out.PodExtraEnvVars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.DBConnection = in.DBConnection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeIdentitySpec.
func (in *NetEyeIdentitySpec) DeepCopy() *NetEyeIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeList) DeepCopyInto(out *NetEyeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetEye, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeList.
func (in *NetEyeList) DeepCopy() *NetEyeList {
	if in == nil {
		return nil
	}
	out := new(NetEyeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetEyeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeOtelCollectorSpec) DeepCopyInto(out *NetEyeOtelCollectorSpec) {
	*out = *in
	if in.ElasticsearchEndpoints != nil {
		in, out := &in.ElasticsearchEndpoints, &out.ElasticsearchEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(NetEyeSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeOtelCollectorSpec.
func (in *NetEyeOtelCollectorSpec) DeepCopy() *NetEyeOtelCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeOtelCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeSecretKeySelector) DeepCopyInto(out *NetEyeSecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeSecretKeySelector.
func (in *NetEyeSecretKeySelector) DeepCopy() *NetEyeSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(NetEyeSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeServiceStatus) DeepCopyInto(out *NetEyeServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeServiceStatus.
func (in *NetEyeServiceStatus) DeepCopy() *NetEyeServiceStatus {
	if in == nil {
		return nil
	}
	out := new(NetEyeServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeServicesStatus) DeepCopyInto(out *NetEyeServicesStatus) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(NetEyeServiceStatus)
		**out = **in
	}
	if in.ElasticStack != nil {
		in, out := &in.ElasticStack, &out.ElasticStack
		*out = new(NetEyeElasticStackStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeServicesStatus.
func (in *NetEyeServicesStatus) DeepCopy() *NetEyeServicesStatus {
	if in == nil {
		return nil
	}
	out := new(NetEyeServicesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeSpec) DeepCopyInto(out *NetEyeSpec) {
	*out = *in
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Identity.DeepCopyInto(&out.Identity)
	if in.ElasticStack != nil {
		in, out := &in.ElasticStack, &out.ElasticStack
		*out = new(NetEyeElasticStackSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeSpec.
func (in *NetEyeSpec) DeepCopy() *NetEyeSpec {
	if in == nil {
		return nil
	}
	out := new(NetEyeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetEyeStatus) DeepCopyInto(out *NetEyeStatus) {
	*out = *in
	in.ServicesStatus.DeepCopyInto(&out.ServicesStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetEyeStatus.
func (in *NetEyeStatus) DeepCopy() *NetEyeStatus {
	if in == nil {
		return nil
	}
	out := new(NetEyeStatus)
	in.DeepCopyInto(out)
	return out
}
