---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: keycloak
type: Opaque
stringData:
  username: neteye-internal-keycloak-admin
  password: "orSM7tpBz3o2KTcmVQdiKWcvuJY0YUz2"