apiVersion: neteye.cloud/v1
kind: KeycloakAuthFlow
metadata:
  name: neteye-idp-discovery-flow2
  namespace: keycloak

spec:
  alias: neteye-idp-discovery-flow2
  realm: master

  executions:
    - requirement: ALTERNATIVE
      authenticator: auth-cookie
      alias: Cookie

    - requirement: ALTERNATIVE
      authenticator: identity-provider-redirector
      alias: neteye-idp-discovery-flow2 adfs
      config:
        alias: adfs
        values:
          defaultProvider: adfs

    - requirement: ALTERNATIVE
      authenticator: home-idp-discovery
      alias: neteye-idp-discovery-flow2 home-idp-discovery
      config:
        alias: home-idp-discovery
        values:
          forwardToFirstMatch: "true"
          bypassLoginPage: "true"
          forwardToLinkedIdp: "false"
          forwardUnverifiedEmail: "true"
          userAttribute: email

    - requirement: DISABLED
      flow:
        alias: neteye-idp-discovery-flow2 Block LDAP logins

        executions:
          - requirement: REQUIRED
            authenticator: conditional-user-attribute
            alias: neteye-idp-discovery-flow2 check-ldap-user
            config:
              alias: check-ldap-user
              values:
                attribute_expected_value: ".+"
                attribute_name: LDAP_ID
                regex: "true"

          - requirement: REQUIRED
            authenticator: deny-access-authenticator
            alias: neteye-idp-discovery-flow2 deny-ldap
            config:
              alias: deny-ldap
              values:
                denyErrorMessage: "Login through pb***** is not supported anymore, please use as username WN***@wgs.wuerth.com or name.surname@wuerth-it.com"

    - requirement: ALTERNATIVE
      flow:
        alias: neteye-idp-discovery-flow2 username-password
        provider: form-flow

        executions:
          - requirement: REQUIRED
            authenticator: auth-username-password-form
            alias: Username Password Form