apiVersion: neteye.cloud/v1
kind: KeycloakAuthFlow
metadata:
  name: neteye-idp-discovery-flow2
  namespace: keycloak

spec:
  alias: neteye-idp-discovery-flow2
  realm: master

  executions:
    - requirement: ALTERNATIVE
      authenticator: auth-cookie
      alias: Cookie

    - requirement: ALTERNATIVE
      authenticator: identity-provider-redirector
      alias: adfs
      config:
        alias: adfs
        config:
          defaultProvider: adfs

    - requirement: ALTERNATIVE
      authenticator: home-idp-discovery
      alias: home-idp-discovery
      config:
        alias: home-idp-discovery
        config:
          forwardToFirstMatch: "true"
          bypassLoginPage: "true"
          forwardToLinkedIdp: "false"
          forwardUnverifiedEmail: "true"
          userAttribute: email

    - requirement: DISABLED
      flow:
        alias: Block LDAP logins
        provider: basic-flow

        executions:
          - requirement: REQUIRED
            authenticator: conditional-user-attribute
            alias: check-ldap-user
            config:
              alias: check-ldap-user
              config:
                attribute_expected_value: ".+"
                attribute_name: LDAP_ID
                regex: "true"

          - requirement: REQUIRED
            authenticator: deny-access-authenticator
            alias: deny-ldap
            config:
              alias: deny-ldap
              config:
                denyErrorMessage: "Login through pb***** is not supported anymore, please use as username WN***@wgs.wuerth.com or name.surname@wuerth-it.com"

    - requirement: ALTERNATIVE
      flow:
        alias: username-password
        provider: form-flow

        executions:
          - requirement: REQUIRED
            authenticator: auth-username-password-form
            alias: Username Password Form