apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manifests
patches:
  - path: release.yaml
    target:
      group: operators.coreos.com
      version: v1alpha1
      kind: ClusterServiceVersion
      name: neteye-operator.v0.0.0
