# Default values for neteye-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  packageName: neteye-operator
  catalogName: neteye-catalog
  catalogImage: 172.19.69.253:5000/neteye-operator-catalog:0.2.0
  versionRange: ">=0.2.0"
  channel: stable
  upgradeConstraintPolicy: CatalogProvided
  pollIntervalMinutes: 10

namespace:
  operators: neteye-system
  system: neteye-system
  olm: olmv1-system
  keycloakOperator: keycloak-system
  tenantShared: neteye-tenant-shared

keycloak:
  enabled: true
  packageName: keycloak-operator
  channel: fast
  catalogName: operatorhubio
  catalogImage: quay.io/operatorhubio/catalog:latest
