# Default values for neteye-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  packageName: neteye-operator
  catalogName: neteye-catalog
  catalogImage: ghcr.io/neteye-platform/neteye-operator-catalog:latest
  versionRange: ">=0.1.0"
  channel: stable
  pollIntervalMinutes: 10

namespace:
  operators: neteye-system
  system: neteye-system
  olm: olmv1-system
  keycloakOperator: keycloak-system
  tenantShared: neteye-tenant-shared

keycloak:
  enabled: true
  packageName: keycloak-operator
  channel: fast
  catalogName: operatorhubio
  catalogImage: quay.io/operatorhubio/catalog:latest
