# Default values for neteye-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  namespace: neteye-system
  packageName: neteye-operator
  catalogName: neteye-catalog
  catalogImage: ghcr.io/neteye-platform/neteye-operator-catalog:latest
  versionRange: ">=0.1.0-alpha7"
  channel: alpha
  upgradeConstraintPolicy: CatalogProvided
  pollIntervalMinutes: 10

keycloak:
  namespace: keycloak-system
  enabled: true
  packageName: keycloak-operator
  channel: fast
  catalogName: operatorhubio
  catalogImage: quay.io/operatorhubio/catalog:latest
