FROM scratch

ARG VERSION
ARG PACKAGE_NAME=neteye-operator

LABEL operators.operatorframework.io.bundle.mediatype.v1="registry+v1"
LABEL operators.operatorframework.io.bundle.manifests.v1="manifests/"
LABEL operators.operatorframework.io.bundle.metadata.v1="metadata/"
LABEL operators.operatorframework.io.bundle.package.v1="${PACKAGE_NAME}"
LABEL operators.operatorframework.io.bundle.version.v1="${VERSION}"
LABEL operators.operatorframework.io.bundle.channels.v1="preview"
LABEL operators.operatorframework.io.bundle.channel.default.v1="preview"

COPY bundle/manifests /manifests/
COPY bundle/metadata /metadata/

USER 1001
