name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@5964e47aa6985b2be528439d1399a70e92d2cec5 # main
    secrets: inherit
