name: Common Cron Checks

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

permissions: write-all

jobs:
  common-cron-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-cron-checks.yaml@55236c148ac5e00c843b2514eb7b3bf73613d245 # main
    secrets: inherit
