name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@5964e47aa6985b2be528439d1399a70e92d2cec5 # main
    secrets: inherit
